### ISSUE TITLE
UNION基表形成的视图是否可以被更新

### ISSUE THREAD

**Issue by wxzjh** [MicrosoftDocs/sql-docs.zh-cn#108]
如果我创建了两张基表，并且创建了一个视图，是两张基表的UNION结果，那么表里的数据能否通过视图来进行修改

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: caab144e-f326-f6b7-aa87-0589c39a9f57
* Version Independent ID: 8b5406c8-9083-af2f-015c-ccbbb502cad6
* Content: [通过视图修改数据 - SQL Server](https://docs.microsoft.com/zh-cn/sql/relational-databases/views/modify-data-through-a-view?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/views/modify-data-through-a-view.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/relational-databases/views/modify-data-through-a-view.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by CeciAc** [comment]
你好，@wxzjh 

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
