### ISSUE TITLE
一处翻译错误 A translation error

### ISSUE THREAD

**Issue by Flithor** [MicrosoftDocs/sql-docs.zh-cn#109]
本文："值可以是 ，则返回 true或false。"
原文："Values can be true or false."
正确翻译："值可以为True或False。"

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c4441c20-dbe9-8f73-a621-c8e4bb2735e0
* Version Independent ID: e623e5de-4bef-000c-11cd-7dab6c07b027
* Content: [sp_spaceused (TRANSACT-SQL) - SQL Server](https://docs.microsoft.com/zh-cn/sql/relational-databases/system-stored-procedures/sp-spaceused-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-spaceused-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/relational-databases/system-stored-procedures/sp-spaceused-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by CeciAc** [comment]
你好，@Flithor
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@Flithor

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/sql/relational-databases/system-stored-procedures/sp-spaceused-transact-sql?view=sql-server-2017#feedback

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
