### ISSUE TITLE
blob类型导致复制失败，求指导，谢谢！（help,oracle blob type   published sqlserver failure）

### ISSUE THREAD

**Issue by loveandnagle** [MicrosoftDocs/sql-docs.zh-cn#110]
============================================

Unable to add item "JHMR_FILE_CONTENT_TEXT".

============================================

An exception occurred while executing a Transact-SQL statement or batch. (Microsoft.SqlServer.ConnectionInfo)

------------------------------
Program location:

   In Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType, Boolean retry)
   In Microsoft.SqlServer.Replication.ReplicationObject.ExecCommand(String commandIn)
   In Microsoft.SqlServer.Replication.Article.CommonArticleCreate()
   In Microsoft.SqlServer.Replication.Article.Create()
   In Microsoft.SqlServer.Management.UI.PubPropArticles.SaveProperties(ExecutionMode& executionResult)

============================================

Unable to publish table 'JHFILE.JHMR_FILE_CONTENT_TEXT' from publisher 'JHEMR'. Please verify the connection information and ensure that you can connect to the publisher through a tool like SQL*PLUS. Make sure that the replication management user schema has the required permissions.
Unable to add publisher triggers and project log tables to the Oracle Publisher for project 'JHMR_FILE_CONTENT_TEXT'. Please verify the connection information and ensure that you can connect to the publisher through a tool like SQL*PLUS. Ensure that the replication management user schema has the required permissions.
The database context has been changed to "distribution".
The OLE DB provider "OraOLEDB.ORACLE" of the linked server "JHEMR" returned the message "ORA-25006: This column cannot be specified in the UPDATE OF clause
ORA-06512: at "REPLUSER.HREPL", line 1722
ORA-06512: At line 1".
Error: 7215, Sev: 17, State: 1, Msg: Unable to execute statement on remote server 'JHEMR'. (.Net SqlClient Data Provider)

------------------------------
For help, click: http://go.microsoft.com/fwlink?ProdName=Microsoft%20SQL%20Server&ProdVer=13.00.1601&EvtSrc=MSSQLServer&EvtID=21790&LinkId=20476

------------------------------
Server Name: SVRUP\MSSQLSERVER1
Error Number: 21790
Seriousty: 16
Status: 1
Process: sp_ORAaddarticle
Line number: 100

------------------------------
Program location:

   In Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
   In Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType, Boolean retry)
==================================================

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: bfa8661c-e5cf-8c4f-48e9-33fe379237a2
* Version Independent ID: 743fb21e-a8d4-5031-d0aa-4aef6587626a
* Content: [Oracle 发布服务器的设计注意事项和限制 - SQL Server](https://docs.microsoft.com/zh-cn/sql/relational-databases/replication/non-sql/design-considerations-and-limitations-for-oracle-publishers?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/replication/non-sql/design-considerations-and-limitations-for-oracle-publishers.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/relational-databases/replication/non-sql/design-considerations-and-limitations-for-oracle-publishers.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by CeciAc** [comment]
你好，@loveandnagle 

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
