### ISSUE TITLE
CONVERT  转换 DateTime 或者 Time 的第三个参数 Style 为什么没有 23 

### ISSUE THREAD

**Issue by yy981420974** [MicrosoftDocs/sql-docs.zh-cn#111]
CONVERT 函数的 Style 参数 在给出的表格中没有 23 的说明。
在 Sql Server Manager Studio 里面使用：select CONVERT(varchar,GETDATE(),23) 可以得到 yyyy-MM-dd 格式的时间

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 1f56efc1-e90f-68dd-cb02-2f2ba21373fd
* Version Independent ID: aa110136-4520-ed90-97fe-1fdedd1863ad
* Content: [CAST 和 CONVERT (Transact-SQL) - SQL Server](https://docs.microsoft.com/zh-cn/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/cast-and-convert-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/t-sql/functions/cast-and-convert-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by CeciAc** [comment]
你好，@yy981420974
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
