### ISSUE TITLE
此说明有误，验证测试不支持：聚集列存储索引现支持 LOB 列 (nvarchar(max)、varchar(max)、varbinary(max))。

### ISSUE THREAD

**Issue by sqlora2019** [MicrosoftDocs/sql-docs.zh-cn#112]
此说明有误，验证测试不支持：聚集列存储索引现支持 LOB 列 (nvarchar(max)、varchar(max)、varbinary(max))。
请核对功能。
https://bbs.csdn.net/topics/392555791

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9547ecaa-d979-ee91-5657-9c302a829d38
* Version Independent ID: baf83ba3-4555-e3ba-123c-adab825200ba
* Content: [数据库引擎中的新增功能 - SQL Server 2017 - SQL Server](https://docs.microsoft.com/zh-cn/sql/database-engine/whats-new-in-sql-server-2017?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/whats-new-in-sql-server-2017.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/database-engine/whats-new-in-sql-server-2017.md)
* Product: **sql**
* Technology: **release-landing**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by CeciAc** [comment]
你好，@sqlora2019
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/sql-docs #2717](https://github.com/MicrosoftDocs/sql-docs/issues/2717) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@sqlora2019

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/sql-docs/issues/2717

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
