### ISSUE TITLE
请简单说明下为什么子查询只能返回单个值。相关关键字简单解释下原因。

### ISSUE THREAD

**Issue by gallop1** [MicrosoftDocs/sql-docs.zh-cn#113]
请简单说明下为什么子查询只能返回单个值。相关关键字简单解释下原因。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b727c932-4a39-5272-80cd-1a5e2b5aca8b
* Version Independent ID: c31a79c4-06d5-749c-1a6d-69e53c929789
* Content: [子查询 (SQL Server) - SQL Server](https://docs.microsoft.com/zh-cn/sql/relational-databases/performance/subqueries?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/performance/subqueries.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/relational-databases/performance/subqueries.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by CeciAc** [comment]
你好，@gallop1
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
