### ISSUE TITLE
datetime2中文页面的存储大小有误

### ISSUE THREAD

**Issue by airaou** [MicrosoftDocs/sql-docs.zh-cn#114]
应为
精度小于 3 的 6 个字节。
精度为 3 和 4 的 7 个字节。
所有其他精度则需要 8 个字节。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: be8724bf-416a-437b-158c-a1f94019a36c
* Version Independent ID: 3b055d34-8d37-cca3-a916-caa43b69af6a
* Content: [datetime2 (Transact-SQL) - SQL Server](https://docs.microsoft.com/zh-cn/sql/t-sql/data-types/datetime2-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/data-types/datetime2-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/t-sql/data-types/datetime2-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by lichasu** [comment]
Issue moved to [MicrosoftDocs/sql-docs #2483](https://github.com/MicrosoftDocs/sql-docs/issues/2483) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lichasu** [comment]
你好，@airaou

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/sql-docs/issues/2483。 

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
