### ISSUE TITLE
安装包下载麻烦

### ISSUE THREAD

**Issue by Hawkeyes0** [MicrosoftDocs/sql-docs.zh-cn#116]
每次更新都要来这里下载这么大个安装包，好痛苦😣！好想可以像Visual Studio那样安装更新啊！或者用Windows Update更新也行啊！或者自己更新自己也行啊！

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [下载 SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/zh-cn/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by srvbpigh** [comment]
Hello, @Hawkeyes0
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@Hawkeyes0
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team

**Comment by nepko** [comment]
下载SQL Server Management Studio 18.3 
链接https://go.microsoft.com/fwlink/?linkid=2104251
自动跳转https://www.microsoft.com/zh-cn/?ref=go

**Comment by karqical2016** [comment]
Download SQL Server Management Studio 18.3.1  https://go.microsoft.com/fwlink/?linkid=2105412
