### ISSUE TITLE
Polygon 接受的实例介绍

### ISSUE THREAD

**Issue by zhangzuozuo** [MicrosoftDocs/sql-docs.zh-cn#117]
在本页面的 接受的实例 的介绍中，
 “要使环可接受，需要满足以下条件：
LineString 实例必须是已接受的实例。
LineString 实例至少必须有四个点。
LineString 实例的起始点和结束点必须相同"

其中的LineString 实例 是否应该是 Polygon 实例。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: fafb07e7-3bab-c01a-409c-71c35c5880e9
* Version Independent ID: 05e7dc27-c520-039d-be50-c4fc91594313
* Content: [Polygon - SQL Server](https://docs.microsoft.com/zh-cn/sql/relational-databases/spatial/polygon?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/spatial/polygon.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/relational-databases/spatial/polygon.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by srvbpigh** [comment]
Hello, @zhangzuozuo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@zhangzuozuo

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/sql-docs/issues/2616

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
