### ISSUE TITLE
pull request 被还原

### ISSUE THREAD

**Issue by wangbin19890524** [MicrosoftDocs/sql-docs.zh-cn#123]
我对该文档提交的修改为什么被还原了？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ac30c0d5-990b-1114-cb66-d6bbb789b698
* Version Independent ID: 9432dace-7676-2a86-485a-dd5bc6568e86
* Content: [SqlPackage.exe - SQL Server](https://docs.microsoft.com/zh-cn/sql/tools/sqlpackage?view=sql-server-2017#feedback)
* Content Source: [docs/tools/sqlpackage.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/tools/sqlpackage.md)
* Product: **sql**
* Technology: **ssdt**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by srvbpigh** [comment]
Hello, @wangbin19890524
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@wangbin19890524

感谢你的反馈和建议。   

该文件当前正在进行翻译。我们将于 <日期> 发布这篇文章。

非常感谢你的支持。 

顺祝商祺！

Microsoft DOCS 全球化体验团队

**Comment by CeciAc** [comment]
https://github.com/MicrosoftDocs/sql-docs-pr/pull/11793
