### ISSUE TITLE
下载链接不可用，被重定向到微软首页

### ISSUE THREAD

**Issue by yb** [MicrosoftDocs/sql-docs.zh-cn#125]
点击 SSMS 18.3 的下载地址 https://go.microsoft.com/fwlink/?linkid=2104251 会重定向到 https://www.microsoft.com/en-us/?ref=go ，无法正常下载。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [下载 SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/zh-cn/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by imba-tjd** [comment]
This has been fixed in https://github.com/MicrosoftDocs/sql-docs/commit/816648720165343d7f830b0a8c428bbb743945b2. The localized page will be synced in a few days. You can use those links in the en-us page before that.

**Comment by srvbpigh** [comment]
Hello, @yb
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by yb** [comment]
Hi @srvbpigh @CeciAc  

I have submitted a pull request #126 to fixed the fwlink and upgrade to the latest version 18.3.1 document.

**Comment by CeciAc** [comment]
Hello, @yb

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue https://github.com/MicrosoftDocs/sql-docs.zh-cn/pull/126 
For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team

**Comment by karqical2016** [comment]
Download SQL Server Management Studio 18.3.1  https://go.microsoft.com/fwlink/?linkid=2105412

**Comment by XgHao** [comment]
把地址栏中“zh-cn”换成“en-us”就可以了，中文页面估计没更新
