### ISSUE TITLE
Update Download SQL Server Management Studio 18.3.1

### ISSUE THREAD

**Issue by karqical2016** [MicrosoftDocs/sql-docs.zh-cn#127]
Download SQL Server Management Studio 18.3.1  https://go.microsoft.com/fwlink/?linkid=2105412

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [下载 SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/zh-cn/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by srvbpigh** [comment]
Hello, @karqical2016
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hello, @karqical2016 

Your contribution is much appreciated. The document is being localized. It will updated soon.

Kind regards,
Microsoft DOCS International Team
