### ISSUE TITLE
下载图标在暗色主题下看起来很奇怪

### ISSUE THREAD

**Issue by Hawkeyes0** [MicrosoftDocs/sql-docs.zh-cn#128]
看起来好像抠图失败的样子，而且图标的颜色与暗色的背景太相似了，以至于我专门切换到亮色主题才知道那是个下载图标😂

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [下载 SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/zh-cn/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by srvbpigh** [comment]
Hello, @Hawkeyes0
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Issue moved to [MicrosoftDocs/sql-docs #3152](https://github.com/MicrosoftDocs/sql-docs/issues/3152) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lichasu** [comment]
你好，@Hawkeyes0

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/sql-docs/issues/3152。 

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
