### ISSUE TITLE
页面布局错误 Page layout bug

### ISSUE THREAD

**Issue by Albych** [MicrosoftDocs/sql-docs.zh-cn#129]
[页面](https://docs.microsoft.com/zh-cn/sql/t-sql/statements/create-statistics-transact-sql?view=sql-server-ver15#e-using-create-statistics-with-fullscan-and-persistsamplepercent) 后的F项误写入E的Code段。
The [Page](https://docs.microsoft.com/zh-cn/sql/t-sql/statements/create-statistics-transact-sql?view=sql-server-ver15#e-using-create-statistics-with-fullscan-and-persistsamplepercent) "F" is in the Code paragraph of E
Thanks.

**Comment by srvbpigh** [comment]
Hello, @Albych
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
你好，@Albych

非常感谢你的参与。我们的团队已评审你的反馈，此问题似乎已有记录。 

请查看问题 #https://github.com/MicrosoftDocs/sql-docs/pull/3338。因此我们将关闭这一重复的问题。 


深深的祝福， 
Microsoft DOCS International Team
