### ISSUE TITLE
Translation Error

### ISSUE THREAD

**Issue by Albych** [MicrosoftDocs/sql-docs.zh-cn#131]
In the section https://docs.microsoft.com/zh-cn/sql/t-sql/database-console-commands/dbcc-checkident-transact-sql?view=sql-server-ver15#d-resetting-the-identity-value-on-an-empty-table ,
>Because the table has no existing rows, the next row inserted will use 1 as the value, that is, the new current identity value, without adding the increment value defined for the column.

While in Chinese:

>因为该表有现有行，因此下一个插入行将使用 1 作为值，即当前标识值（而不会加上为该列定义的增量值）。

It should be "因为该表**没**有现有行"
Thanks.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 34732a03-b910-02a3-2d54-ad429b1ca137
* Version Independent ID: bd0c8d93-ebfd-f87c-7985-890b9d43182a
* Content: [DBCC CHECKIDENT (Transact-SQL) - SQL Server](https://docs.microsoft.com/zh-cn/sql/t-sql/database-console-commands/dbcc-checkident-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/database-console-commands/dbcc-checkident-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/t-sql/database-console-commands/dbcc-checkident-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @pmasl
* Microsoft Alias: **umajay**

**Comment by srvbpigh** [comment]
Hello, @Albych
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @Albych,
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/sql/t-sql/database-console-commands/dbcc-checkident-transact-sql?view=sql-server-ver15. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
