### ISSUE TITLE
增添新内容并更正文章错误

### ISSUE THREAD

**Issue by yupengcheng0719** [MicrosoftDocs/sql-docs.zh-cn#132]
增加&lt;nnn&gt; 标识版本190和SQL Server 2019 (15.x)，更正文章以下各个对于 SQL Server 2019的实例名

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b3ca4320-49c8-31a4-84c6-0185ba176216
* Version Independent ID: 04a1843f-813d-fe8e-611b-af6ada02ef01
* Content: [SQL Server 的默认实例和命名实例的文件位置 - SQL Server](https://docs.microsoft.com/zh-cn/sql/sql-server/install/file-locations-for-default-and-named-instances-of-sql-server?redirectedfrom=MSDN&view=sql-server-ver15#feedback)
* Content Source: [docs/sql-server/install/file-locations-for-default-and-named-instances-of-sql-server.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/sql-server/install/file-locations-for-default-and-named-instances-of-sql-server.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by srvbpigh** [comment]
Hello, @yupengcheng0719
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-maudel** [comment]
Issue moved to [MicrosoftDocs/sql-docs #3559](https://github.com/MicrosoftDocs/sql-docs/issues/3559) via [**ZenHub**](https://www.zenhub.com/)

**Comment by v-maudel** [comment]
你好，@yupengcheng0719

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 -https://github.com/MicrosoftDocs/sql-docs/issues/3559 。 

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
