### ISSUE TITLE
cai

### ISSUE THREAD

**Issue by martin-315** [MicrosoftDocs/sql-docs.zh-cn#133]
踩踩踩踩踩踩

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c90a9561-bef5-25e8-e672-ed0d4493a383
* Version Independent ID: 16c705c1-55be-d339-8326-51d57cb0fd69
* Content: [Transact-SQL 参考（数据库引擎） - SQL Server](https://docs.microsoft.com/zh-cn/sql/t-sql/language-reference?view=sql-server-ver15)
* Content Source: [docs/t-sql/language-reference.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/t-sql/language-reference.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by srvbpigh** [comment]
Hello, @martin-315
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
empty feedback
