### ISSUE TITLE
sqlserver中的python能否支持用matplotlib来绘制图形

### ISSUE THREAD

**Issue by dqaudithillstone** [MicrosoftDocs/sql-docs.zh-cn#135]
[EXECUTE sp_execute_external_script
  @language = N'Python',
 @script = N'
import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(-20, 20, 100) 
y=np.sin(x)
plt.plot(x,y)       
plt.show() 
'
sqlserver中的python是否支持绘制图形
]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0520afec-120b-78ee-a57c-7dc20771b202
* Version Independent ID: 4a79f474-9bba-6fbc-30dd-221997f9dbc0
* Content: [SQL Server 机器学习服务中的新增功能？](https://docs.microsoft.com/zh-cn/sql/advanced-analytics/what-s-new-in-sql-server-machine-learning-services?view=sql-server-2017)
* Content Source: [docs/advanced-analytics/what-s-new-in-sql-server-machine-learning-services.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/advanced-analytics/what-s-new-in-sql-server-machine-learning-services.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by srvbpigh** [comment]
Hello, @dqaudithillstone
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
你好，@dqaudithillstone， 

非常感谢您的贡献。此反馈与产品相关，请使用“文档”页底部的“提供产品反馈”按钮，记录你的建议。 

如果你有任何与文档相关的反馈，请通过此渠道进行记录。 

我们非常感谢你对我们的文章的贡献。 

Microsoft DOCS 国际团队
