### ISSUE TITLE
Simplified Chinese Version, Database Support ICON is misplaced

### ISSUE THREAD

**Issue by nomorewzx** [MicrosoftDocs/sql-docs.zh-cn#136]
In Simplified Chinese Version of this page, the Database Support ICON is placed after the database service name instead of before the names, and this is confusing.

Please see: https://docs.microsoft.com/zh-cn/sql/relational-databases/system-stored-procedures/sp-rename-transact-sql?view=sql-server-ver15

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: fef51473-c5ad-3fe8-64c2-092795cbcad5
* Version Independent ID: 3138756b-3dd0-c23c-9bbc-860652830672
* Content: [sp_rename （Transact-sql） - SQL Server](https://docs.microsoft.com/zh-cn/sql/relational-databases/system-stored-procedures/sp-rename-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-rename-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/relational-databases/system-stored-procedures/sp-rename-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by srvbpigh** [comment]
Hello, @nomorewzx
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @nomorewzx,

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @nomorewzx,

We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team

**Comment by nomorewzx** [comment]
Hi,

Sorry for late reply, the attached screenshot may explain the issue.


The icon ✅ is placed after the database name in Simplified Chinese Version of the doc. I do not know if this is designed, but the icon position is pretty confused.

I thought the Azure Synapse Analytics does support this feature at first and had to re-check the document after I tried and found that Azure Synapse Analytics does not support the feature. 

<img width="1665" alt="support_not_support_icon" src="https://user-images.githubusercontent.com/3294078/74121308-08d45480-4c02-11ea-916a-8c02b3907e18.png">

Thanks and best regards

**Comment by ticianaciminari** [comment]
@nomorewzx Thank you for your feedback. 

Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/sql/relational-databases/system-stored-procedures/sp-rename-transact-sql?view=sql-server-ver15.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 

Microsoft DOCS International Team
