### ISSUE TITLE
mssql `zh-cn` pages' table element style is missing, because js throw an exception.

### ISSUE THREAD

**Issue by heroboy** [MicrosoftDocs/sql-docs.zh-cn#137]
反正是中文页面，下面说中文。
英文版的是好的。chrome firefox都这样。
```
modify-tables.ts:200 Uncaught (in promise) TypeError: Cannot read property 'nodeName' of null
    at qh (modify-tables.ts:200)
    at modify-tables.ts:188
    at modify-tables.ts:131
    at Array.forEach (&lt;anonymous&gt;)
    at Ph (modify-tables.ts:128)
    at Nh (index.ts:9)
    at index-docs.ts:168
```

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: dae81d65-f7b9-7a97-7fe7-30775f815e5b
* Version Independent ID: d4d339e7-48d7-d159-eb59-13bdedc25b4c
* Content: [事务锁定和行版本控制指南 - SQL Server](https://docs.microsoft.com/zh-cn/sql/relational-databases/sql-server-transaction-locking-and-row-versioning-guide?view=sql-server-ver15)
* Content Source: [docs/relational-databases/sql-server-transaction-locking-and-row-versioning-guide.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/relational-databases/sql-server-transaction-locking-and-row-versioning-guide.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by srvbpigh** [comment]
Hello, @heroboy
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
你好，@heroboy ， 

我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？ 

顺祝商祺！ 

Microsoft DOCS 国际团队

**Comment by heroboy** [comment]
不可以，因为我刚刚访问这个页面的时候发现表格的样式已经正确了，并且控制台没有这个报错了。

**Comment by V-vafune** [comment]
你好，@heroboy  

非常感谢你提供反馈。很高兴我们的文档满足你的期望。  

欢迎提供宝贵的反馈，以便我们继续改进体验。  
 
深深的祝福，  

Microsoft DOCS International Team
