### ISSUE TITLE
笔误-英文版和中文版不一致

### ISSUE THREAD

**Issue by Nate-Robinson** [MicrosoftDocs/sql-docs.zh-cn#140]
此处似乎有一个笔误，
https://docs.microsoft.com/zh-cn/sql/t-sql/language-elements/like-transact-sql?view=sql-server-ver15#using-wildcard-characters-as-literals
将下划线当作普通字符时，举例的表格中应该是 LIKE '[_]n'，此处写成了 LIKE '[]n'。
我对比了英文版，以及在 SQL Server Management Studio 中测试，应该是此处有笔误。let me know if I was wrong.

 

https://docs.microsoft.com/en-us/sql/t-sql/language-elements/like-transact-sql?view=sql-server-ver15#using-wildcard-characters-as-literals

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b5353a04-2e20-ae05-2004-6fd8a19c440a
* Version Independent ID: 382b0acd-1e14-c7fd-bf92-c3e09ccdf4fa
* Content: [LIKE (Transact-SQL) - SQL Server](https://docs.microsoft.com/zh-cn/sql/t-sql/language-elements/like-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/language-elements/like-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/t-sql/language-elements/like-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by srvbpigh** [comment]
Hello, @Nate-Robinson
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@Nate-Robinson

感谢你的反馈。  


我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：XXX。   


非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。  


深深的祝福，  

Microsoft DOCS International Team
