### ISSUE TITLE
建表的时候不能通过输入的字母模糊带出类型

### ISSUE THREAD

**Issue by 109918799** [MicrosoftDocs/sql-docs.zh-cn#141]
建表字段类型为 nvarchar的类型，18.2版本的时候只要输入nv就能自动带出后面的类型 ，现在的版本不能带出来，希望能修正，这个功能还是很方便用户

**Comment by 109918799** [comment]
建表字段类型为 nvarchar的类型，18.2版本的时候只要输入nv就能自动带出后面的类型 ，现在的版本不能带出来，希望能修正，这个功能还是很方便用户

**Comment by srvbpigh** [comment]
Hello, @109918799
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/sql-docs #4609](https://github.com/MicrosoftDocs/sql-docs/issues/4609) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
你好，@109918799 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/sql-docs/issues/4609。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
