### ISSUE TITLE
Warnings 和 Type 两个参数名在中文板块中被翻译成 “警告” 和“类型”

### ISSUE THREAD

**Issue by YuanjianZhang** [MicrosoftDocs/sql-docs.zh-cn#142]
不应该将参数名翻译

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 939d7e8e-a535-a581-ae73-d6850d8e817d
* Version Independent ID: 943d5956-b3e1-ea01-ed1a-83ab13ab1cc6
* Content: [SET SHOWPLAN_ALL (Transact-SQL) - SQL Server](https://docs.microsoft.com/zh-cn/sql/t-sql/statements/set-showplan-all-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/set-showplan-all-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/t-sql/statements/set-showplan-all-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
Thank you. Addressing now in a PR - should be fixed in the US version. I do not know how long it takes to show up on the localized version. Will investigate.

**Comment by srvbpigh** [comment]
Hello, @YuanjianZhang
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CarlRabeler** [comment]
International team – please see https://github.com/MicrosoftDocs/sql-docs-pr/pull/14748

**Comment by CarlRabeler** [comment]
#please-close

**Comment by CarlRabeler** [comment]
#close
