### ISSUE TITLE
STStartPoint 文档sql语句错误

### ISSUE THREAD

**Issue by zLulus** [MicrosoftDocs/sql-docs.zh-cn#143]
[STStartPoint（geometry 数据类型）](https://docs.microsoft.com/zh-cn/sql/t-sql/spatial-geometry/ststartpoint-geometry-data-type?view=sql-server-ver15)    
```sql
DECLARE @g geometry;  
SET @g = geometry::STGeomFromText('LINESTRING(0 0, 2 2, 1 0)', 0;  
SELECT @g.STStartPoint().ToString();  
```
应该改为
```sql
SET @g = geometry::STGeomFromText('LINESTRING(0 0, 2 2, 1 0)', 0);  
```

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e46d0079-02e5-e0ba-8d64-93030fa6ddf7
* Version Independent ID: 4a0eff3a-0396-795b-a413-48d8805bf12e
* Content: [STStartPoint（geometry 数据类型） - SQL Server](https://docs.microsoft.com/zh-cn/sql/t-sql/spatial-geometry/ststartpoint-geometry-data-type?view=sql-server-ver15)
* Content Source: [docs/t-sql/spatial-geometry/ststartpoint-geometry-data-type.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/t-sql/spatial-geometry/ststartpoint-geometry-data-type.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by srvbpigh** [comment]
Hello, @zLulus
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
你好，@zLulus 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/sql-docs/issues/4769。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
