### ISSUE TITLE
关于数据配置分发的反馈

### ISSUE THREAD

**Issue by billcoding** [MicrosoftDocs/sql-docs.zh-cn#144]
1、我在本地数据库主机上配置了分发服务器
![image](https://user-images.githubusercontent.com/21271780/81693042-e4eb0e00-9491-11ea-8833-ca89eb204ad0.png)
2、然后“本地发布”->"新建发布"确提示
![image](https://user-images.githubusercontent.com/21271780/81693179-1f54ab00-9492-11ea-99c0-2f581e0e3af3.png)

请问这个问题如何解决？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5638a498-67b5-8e1f-e60d-77e80fb122f9
* Version Independent ID: 22171cdd-c1d9-29cc-a67d-9d5fcfb68d52
* Content: [教程：配置复制 (T-SQL) - SQL Server on Linux](https://docs.microsoft.com/zh-cn/sql/linux/sql-server-linux-replication-tutorial-tsql?view=sql-server-ver15#feedback)
* Content Source: [docs/linux/sql-server-linux-replication-tutorial-tsql.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/linux/sql-server-linux-replication-tutorial-tsql.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by srvbpigh** [comment]
Hello, @billcoding
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
你好，@billcoding  

感谢你的反馈。  

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/sql/linux/sql-server-linux-replication-tutorial-tsql?view=sql-server-ver15#feedback。   

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。  

深深的祝福，  
Microsoft DOCS International Team
