### ISSUE TITLE
get token  error

### ISSUE THREAD

**Issue by amwwgjj** [MicrosoftDocs/sql-docs.zh-cn#155]
[在此处输入反馈]

> azdata app describe -n add-app -v v1
{
  "input_param_defs": [
    {
      "name": "x",
      "type": "int"
    },
    {
      "name": "y",
      "type": "int"
    }
  ],
  "internal_name": "app1",
  "links": {
    "app": "https://172.16.126.72:30080/api/v1/app/add-app/v1",
    "swagger": "https://172.16.126.72:30080/api/v1/app/add-app/v1/swagger.json"
  },
  "name": "add-app",
  "output_param_defs": [
    {
      "name": "result",
      "type": "int"
    }
  ],
  "state": "Ready",
  "version": "v1"
}

使用https://172.16.126.72:30080/api/v1/token 获取 token
报：Could not get any response

![token](https://user-images.githubusercontent.com/4329007/82728288-08c81280-9d22-11ea-83b0-6207c51d4581.jpg)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 8546addb-1209-b474-62c8-3efe0967739f
* Version Independent ID: cc4639e5-93d2-0203-ff74-26e6f2fb82b6
* Content: [使用应用程序 - SQL Server Big Data Clusters](https://docs.microsoft.com/zh-cn/sql/big-data-cluster/big-data-cluster-consume-apps?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/big-data-cluster-consume-apps.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/big-data-cluster/big-data-cluster-consume-apps.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @jeroenterheerdt
* Microsoft Alias: **jterh**

**Comment by srvbpigh** [comment]
Hello, @amwwgjj
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
你好，@amwwgjj， 

我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？ 

顺祝商祺！ 

Microsoft DOCS 国际团队

**Comment by V-vafune** [comment]
你好，@amwwgjj ， 

我们正在跟进我们之前的评论。为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？ 

顺祝商祺！ 

Microsoft DOCS 国际团队

**Comment by CeciAc** [comment]
你好，@amwwgjj
再次感谢你的评论。
很遗憾，我们仍然缺少信息，无法处理你的反馈。我们当前将关闭此 GitHub 问题，但我们欢迎你在以后提交更多反馈。
顺祝商祺！
Microsoft DOCS 国际团队
